[package]
name = "shogi_cards"
version = "0.1.0"
authors = ["storyfeet <thebeaky@psmail.net>"]
edition = "2018"

[dependencies]
clap_conf= {path="../../mlibs/clap_conf/"}
serde = "1.0.90"
serde_derive = "1.0.90"
toml =  "0.5.0"
mksvg = {path="../../mlibs/mksvg/"}
